#!/bin/sh

### BEGIN INIT INFO
# Provides:          foreverb
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: foreverb initscript
# Description:       foreverb
### END INIT INFO

# Do NOT "set -e"

DAEMON="foreverb"
SCRIPT_NAME="/etc/init.d/foreverb"

case "$1" in
  start | stop | restart )
  su -c "$DAEMON $1 --all --yes"
  ;;
  *)
  echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
  exit 3
  ;;
esac

:

